name: nutrilens
description: AI-powered nutrition tracking with photo and text analysis
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.3.0
  
  # Navigation
  go_router: ^13.0.0
  
  # Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Storage & Security
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.0
  path_provider: ^2.1.0
  
  # Image Handling
  image_picker: ^1.0.0
  image: ^4.1.0
  
  # API & Networking
  dio: ^5.4.0
  
  # UI Components
  cached_network_image: ^3.3.0
  
  # Charts & Analytics
  fl_chart: ^0.68.0
  
  # Utilities
  intl: ^0.18.0
  collection: ^1.18.0
  share_plus: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.0
  hive_generator: ^2.0.1
  riverpod_generator: ^2.3.0

flutter:
  uses-material-design: true